language: python

os:
  - linux
  - osx
  - windows

osx_image: xcode10

env:
  - TOXENV: py37
    dist: xenial
    sudo: true
  - TOXENV: py27
  - TOXENV: other

install:
  - pip install tox

script:
  - tox
