language: python

os:
  - linux
  - osx
  - windows

dist: xenial
sudo: true

osx_image: xcode10

python:
  - 3.7
  - 2.7

env:
  - TOXENV:
  - TOXENV: other

install:
  - pip install tox
  - pip install tox-travis

script:
  - tox
