language: python

os:
  - linux
  - osx
  - windows

dist: xenial
sudo: true

osx_image: xcode10

env:
  - TOXENV: py37
  - TOXENV: py27
  - TOXENV: other

install:
  - pip install tox

script:
  - tox
